### ISSUE TITLE
2.2 Class Diagram

### ISSUE THREAD

**Issue by whoistfq** [INF2001/TEAM-PROJECT-P11-3#85]
1. Task title ID: #85
2. What is the task about?  **Using Object Oriented (OO) languages to create a class diagram**
3. What are the goals of the task?  **To create a class diagram based on the requirements from M1**
4. Success or completion criteria. **Completion of class diagram that covers all the requirements from M1**
5. Allocated time:  **3 days**
6. Start date and end date of the issue/task. **Start: 15/10/23 , End: 17/10/23** 
7. Who is the owner? **Taufiq & Clement**
8. The status of the task. **In Progress**
9. What is the Priority of the task? **High**

**Comment by donhitme34** [comment]
1. The UML class diagram has been completed in order to assist with the future sequence diagram creation as well as follow based on the project specifications and requirements thus far
2. The diagram has been uploaded to the project github's repository.
3. The task does not affect the completion timeline of the project
4. There are no changes to the completion of the task
5. Start: 15/10/23 , End: 16/10/23
